### ISSUE TITLE
SQL injection

### ISSUE THREAD

**Issue by kolayne** [enghamzasalem/Create_db_faker#1]
This piece of code is vulnerable to SQL injections:
https://github.com/enghamzasalem/Create_db_faker/blob/d82c7616a7aa13766d155857092da389479e2ecf/createFaker.py#L20

See the psycopg [docs](https://www.psycopg.org/docs/usage.html#passing-parameters-to-sql-queries) for more information

**Comment by enghamzasalem** [comment]
Can you contribute a modification? if yes; fork and modify, will push it as new branch
